// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN8oMijLXBLm6eN2u9cFP9K6bhk0Buvn0',
    appId: '1:636349216762:web:7f462d13c01ab83fb61643',
    messagingSenderId: '636349216762',
    projectId: 'ruzai-caac6',
    authDomain: 'ruzai-caac6.firebaseapp.com',
    storageBucket: 'ruzai-caac6.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyyijk0M6rxUO0CLf6_MDOfSP-cxb5Swg',
    appId: '1:636349216762:android:dff0affa6a8833e4b61643',
    messagingSenderId: '636349216762',
    projectId: 'ruzai-caac6',
    storageBucket: 'ruzai-caac6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsLdpx-MJPr47o459AdyAJmLhOytUTiUo',
    appId: '1:636349216762:ios:1aa263ac7d219267b61643',
    messagingSenderId: '636349216762',
    projectId: 'ruzai-caac6',
    storageBucket: 'ruzai-caac6.firebasestorage.app',
    iosClientId: '636349216762-rs6clqjv0fljjt75ij2kntmln3atpqs9.apps.googleusercontent.com',
    iosBundleId: 'com.example.ruzai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsLdpx-MJPr47o459AdyAJmLhOytUTiUo',
    appId: '1:636349216762:ios:1aa263ac7d219267b61643',
    messagingSenderId: '636349216762',
    projectId: 'ruzai-caac6',
    storageBucket: 'ruzai-caac6.firebasestorage.app',
    iosClientId: '636349216762-rs6clqjv0fljjt75ij2kntmln3atpqs9.apps.googleusercontent.com',
    iosBundleId: 'com.example.ruzai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN8oMijLXBLm6eN2u9cFP9K6bhk0Buvn0',
    appId: '1:636349216762:web:b6cfe4b315946489b61643',
    messagingSenderId: '636349216762',
    projectId: 'ruzai-caac6',
    authDomain: 'ruzai-caac6.firebaseapp.com',
    storageBucket: 'ruzai-caac6.firebasestorage.app',
  );
}
